### ISSUE TITLE
[FaloopIntegration] S-rank "Kaiser Behemoth" keeps teleporting to Behemoth server

### ISSUE THREAD

**Issue by JodanJodan** [SlashNephy/Divination#683]
**Which plugin are you referring to?**
FaloopIntegration

**Describe the bug**
When `kaiser behemoth` spawns on a server, clicking `Teleport` in the `Active Mobs` window teleports to the Behemoth server.

**To Reproduce**
1. Wait for Kaiser Behemoth to spawn on a non-Behemoth server
2. Click `Teleport` in the `Active Mobs` window

**Expected behavior**
It should teleport to the correct server and location.

**Screenshots**
![image](https://github.com/user-attachments/assets/0487c36e-3d81-406f-bbdd-64871f5b1e7d)

**Comment by Diyagi** [comment]
While this is similar to the other issue, i think theres no reason for this to happen with the FaloopIntegration Active Mobs UI, that other issue is due to chat message parsing, faloopintegration has the data already ready and sending it thru the IPC should not result in the wrong world being selected.
